# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: oil lala

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/check-in

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: Hallo Hello, anyone up for a chat?

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |oh hello
          echo Add other run2 actions knock at the door to chat to run,
          echo test run2 gorgeous, and display his body once in.
